package game;

import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.util.Locale;

/**
 * Developer-only runtime facade for the N64 Mario equipment workbench.
 *
 * This class deliberately does not become equipment/render authority. It exposes
 * the already-owned Mario helmet calibration, presentation freeze and a temporary
 * geometric head-mask preview to the Swing developer console.
 */
public final class MarioEquipmentWorkbench {

    private static final int EQUIPMENT_SLOT_HAT = 0;
    private static final int EQUIP_SLOT_DECODE_MULTIPLIER = -917104297;

    private static volatile boolean headMaskEnabled;
    private static volatile boolean maskOnlyWithHelmet = true;
    private static volatile float maskStartFraction = 0.72F;
    private static volatile float maskRadiusFraction = 0.40F;

    private static volatile long preparedMaskSequence = Long.MIN_VALUE;
    private static volatile float maskCenterX;
    private static volatile float maskCenterZ;
    private static volatile float maskStartY;
    private static volatile float maskRadiusSquared;
    private static volatile int lastMaskedTriangles;

    private MarioEquipmentWorkbench() {
    }

    public static Snapshot getSnapshot() {
        HelmetInfo helmet = findVisibleHelmet();
        int itemId = helmet == null ? -1 : helmet.itemId;
        MarioHelmetCalibrationController.Snapshot calibration =
                itemId < 0
                        ? MarioHelmetCalibrationController.Snapshot.DEFAULT
                        : MarioHelmetCalibrationController.getSnapshot(itemId);

        Sm64BridgeSession.GeometryFrame frame = Sm64BridgeSession.getLatestGeometryFrame();
        float faceAngle = frame == null || frame.state == null
                ? Float.NaN : frame.state.faceAngle;

        return new Snapshot(
                PlayerControllerMode.isMarioMode(),
                itemId,
                helmet == null ? "-" : helmet.name,
                calibration.scaleMultiplier,
                calibration.offsetX,
                calibration.offsetY,
                calibration.offsetZ,
                calibration.yawDegrees,
                Sm64BridgeSession.isPresentationFrozen(),
                MarioHeadOrientationTracker.hasReference(),
                faceAngle,
                headMaskEnabled,
                maskOnlyWithHelmet,
                maskStartFraction * 100.0F,
                maskRadiusFraction * 100.0F,
                lastMaskedTriangles);
    }

    public static void setScale(float value) {
        updateCalibration(value, null, null, null, null);
    }

    public static void setOffsetX(float value) {
        updateCalibration(null, value, null, null, null);
    }

    public static void setOffsetY(float value) {
        updateCalibration(null, null, value, null, null);
    }

    public static void setOffsetZ(float value) {
        updateCalibration(null, null, null, value, null);
    }

    public static void setYawDegrees(float value) {
        updateCalibration(null, null, null, null, value);
    }

    public static void flipHelmetYaw180() {
        Snapshot snapshot = getSnapshot();
        if (snapshot.itemId >= 0) {
            setYawDegrees(normalizeDegrees(snapshot.yawDegrees + 180.0F));
        }
    }

    public static void resetHelmetTransform() {
        Snapshot snapshot = getSnapshot();
        if (snapshot.itemId >= 0) {
            MarioHelmetCalibrationController.resetItem(snapshot.itemId);
        }
    }

    public static void setPresentationFrozen(boolean frozen) {
        Sm64BridgeSession.setPresentationFrozen(frozen);
    }

    public static void setHeadMaskEnabled(boolean enabled) {
        headMaskEnabled = enabled;
    }

    public static void setMaskOnlyWithHelmet(boolean enabled) {
        maskOnlyWithHelmet = enabled;
    }

    public static void setMaskStartPercent(float percent) {
        maskStartFraction = clamp(percent / 100.0F, 0.50F, 0.95F);
    }

    public static void setMaskRadiusPercent(float percent) {
        maskRadiusFraction = clamp(percent / 100.0F, 0.10F, 0.75F);
    }

    public static void resetHeadMask() {
        headMaskEnabled = false;
        maskOnlyWithHelmet = true;
        maskStartFraction = 0.72F;
        maskRadiusFraction = 0.40F;
        lastMaskedTriangles = 0;
    }

    public static String formatProfileMarkdown() {
        Snapshot value = getSnapshot();
        StringBuilder out = new StringBuilder(1024);
        out.append("# Mario Equipment Runtime Profile\n\n");
        out.append("Generated by the Matrix3 N64 Equipment Workbench.\n\n");
        out.append("## Active helmet\n\n");
        out.append("- Item: ").append(value.itemId < 0 ? "none" : value.itemId).append('\n');
        out.append("- Name: ").append(value.itemName).append('\n');
        out.append("- Scale multiplier: ").append(format(value.scale)).append('\n');
        out.append("- Head-local X: ").append(format(value.x)).append('\n');
        out.append("- Head-local Y: ").append(format(value.y)).append('\n');
        out.append("- Head-local Z: ").append(format(value.z)).append('\n');
        out.append("- Yaw delta degrees: ").append(format(value.yawDegrees)).append('\n');
        out.append("- Presentation frozen: ").append(value.frozen).append('\n');
        out.append("- 3D head basis available: ").append(value.head3d).append('\n');
        out.append("- Native faceAngle radians: ").append(format(value.faceAngle)).append("\n\n");
        out.append("## Mario head mask\n\n");
        out.append("- Enabled: ").append(value.maskEnabled).append('\n');
        out.append("- Only with helmet: ").append(value.maskOnlyWithHelmet).append('\n');
        out.append("- Start height percent: ").append(format(value.maskStartPercent)).append('\n');
        out.append("- Radius percent: ").append(format(value.maskRadiusPercent)).append('\n');
        out.append("- Last masked source triangles: ").append(value.maskedTriangles).append("\n\n");
        out.append("## Transform convention\n\n");
        out.append("Authoritative convention notes: `docs/n64/TRANSFORM_CONVENTIONS.md`.\n\n");
        out.append("The original V4 animated head delta was runtime-verified to move in the opposite direction. ")
                .append("The corrected renderer therefore uses the inverse rotation (matrix transpose) for the rigid head delta.\n");
        return out.toString();
    }

    /**
     * Saves a local developer snapshot beside the tracked N64 documentation.
     * This is intentionally explicit and user-triggered; normal rendering never
     * writes project files.
     */
    public static String saveProfileMarkdown() {
        File file = resolveProfileFile();
        Writer writer = null;
        try {
            File parent = file.getParentFile();
            if (parent != null && !parent.isDirectory() && !parent.mkdirs()) {
                return "Could not create " + parent.getPath();
            }
            writer = new OutputStreamWriter(
                    new FileOutputStream(file, false), StandardCharsets.UTF_8);
            writer.write(formatProfileMarkdown());
            writer.flush();
            return file.getAbsolutePath();
        } catch (Exception ex) {
            return "Save failed: " + ex.getClass().getSimpleName() + ": " + ex.getMessage();
        } finally {
            if (writer != null) {
                try {
                    writer.close();
                } catch (Exception ignored) {
                    // Developer save cleanup only.
                }
            }
        }
    }

    /** Called once before a Mario model build so per-triangle masking stays cheap. */
    static void prepareMaskFrame(Sm64BridgeSession.GeometryFrame frame) {
        if (frame == null || frame.state == null || frame.positions == null
                || frame.triangleCount <= 0
                || frame.positions.length < frame.triangleCount * 9) {
            preparedMaskSequence = Long.MIN_VALUE;
            lastMaskedTriangles = 0;
            return;
        }
        if (preparedMaskSequence == frame.sequence) {
            return;
        }

        int totalVertices = frame.triangleCount * 3;
        float minX = Float.POSITIVE_INFINITY;
        float minY = Float.POSITIVE_INFINITY;
        float minZ = Float.POSITIVE_INFINITY;
        float maxX = Float.NEGATIVE_INFINITY;
        float maxY = Float.NEGATIVE_INFINITY;
        float maxZ = Float.NEGATIVE_INFINITY;
        for (int vertex = 0; vertex < totalVertices; vertex++) {
            int base = vertex * 3;
            float x = frame.positions[base] - frame.state.x;
            float y = frame.positions[base + 1] - frame.state.y;
            float z = frame.positions[base + 2] - frame.state.z;
            if (x < minX) minX = x;
            if (x > maxX) maxX = x;
            if (y < minY) minY = y;
            if (y > maxY) maxY = y;
            if (z < minZ) minZ = z;
            if (z > maxZ) maxZ = z;
        }

        float height = maxY - minY;
        float width = maxX - minX;
        float depth = maxZ - minZ;
        if (!finite(height) || height <= 0.0F) {
            preparedMaskSequence = Long.MIN_VALUE;
            lastMaskedTriangles = 0;
            return;
        }

        maskCenterX = (minX + maxX) * 0.5F;
        maskCenterZ = (minZ + maxZ) * 0.5F;
        maskStartY = minY + height * maskStartFraction;
        float radius = Math.max(width, depth) * maskRadiusFraction;
        maskRadiusSquared = radius * radius;
        preparedMaskSequence = frame.sequence;
        lastMaskedTriangles = 0;
    }

    static boolean shouldMaskTriangle(
            Sm64BridgeSession.GeometryFrame frame,
            int sourceTriangle) {
        if (!headMaskEnabled || frame == null || preparedMaskSequence != frame.sequence) {
            return false;
        }
        if (maskOnlyWithHelmet && findVisibleHelmet() == null) {
            return false;
        }
        if (sourceTriangle < 0 || sourceTriangle >= frame.triangleCount) {
            return false;
        }
        int base = sourceTriangle * 9;
        float x = ((frame.positions[base] + frame.positions[base + 3] + frame.positions[base + 6]) / 3.0F)
                - frame.state.x;
        float y = ((frame.positions[base + 1] + frame.positions[base + 4] + frame.positions[base + 7]) / 3.0F)
                - frame.state.y;
        float z = ((frame.positions[base + 2] + frame.positions[base + 5] + frame.positions[base + 8]) / 3.0F)
                - frame.state.z;
        float dx = x - maskCenterX;
        float dz = z - maskCenterZ;
        return y >= maskStartY && dx * dx + dz * dz <= maskRadiusSquared;
    }

    static void recordMaskedTriangleCount(int count) {
        lastMaskedTriangles = Math.max(0, count);
    }

    private static void updateCalibration(
            Float scale,
            Float x,
            Float y,
            Float z,
            Float yaw) {
        Snapshot workbench = getSnapshot();
        if (workbench.itemId < 0) {
            return;
        }
        MarioHelmetCalibrationController.Snapshot current =
                MarioHelmetCalibrationController.getSnapshot(workbench.itemId);
        MarioHelmetCalibrationController.setSnapshot(
                workbench.itemId,
                new MarioHelmetCalibrationController.Snapshot(
                        scale == null ? current.scaleMultiplier : scale.floatValue(),
                        x == null ? current.offsetX : x.floatValue(),
                        y == null ? current.offsetY : y.floatValue(),
                        z == null ? current.offsetZ : z.floatValue(),
                        yaw == null ? current.yawDegrees : yaw.floatValue()));
    }

    private static HelmetInfo findVisibleHelmet() {
        Player player = Class611.aClass456_Sub1_Sub2_Sub3_Sub2_7976;
        if (player == null || player.aClass474_11831 == null
                || player.aClass474_11831.anIntArray5317 == null) {
            return null;
        }
        int[] parts = player.aClass474_11831.anIntArray5317;
        for (int encoded : parts) {
            if ((encoded & 0x40000000) == 0) {
                continue;
            }
            int itemId = encoded & 0x3fffffff;
            ItemDefinitions definition = (ItemDefinitions) Class672.aClass639_Sub5_8533
                    .getDefinition(itemId, -1597715602);
            if (definition != null
                    && definition.equipSlot * EQUIP_SLOT_DECODE_MULTIPLIER == EQUIPMENT_SLOT_HAT) {
                String name = definition.aString8180;
                return new HelmetInfo(itemId,
                        name == null || name.trim().isEmpty() ? "unknown" : name);
            }
        }
        return null;
    }

    private static File resolveProfileFile() {
        File direct = new File("docs/n64/MARIO_EQUIPMENT_RUNTIME.md");
        File directParent = direct.getParentFile();
        if (directParent != null && directParent.isDirectory()) {
            return direct;
        }
        File parent = new File("../docs/n64/MARIO_EQUIPMENT_RUNTIME.md");
        File parentDir = parent.getParentFile();
        if (parentDir != null && parentDir.isDirectory()) {
            return parent;
        }
        return direct;
    }

    private static float normalizeDegrees(float value) {
        if (!finite(value)) {
            return 0.0F;
        }
        while (value > 180.0F) value -= 360.0F;
        while (value < -180.0F) value += 360.0F;
        return value;
    }

    private static float clamp(float value, float min, float max) {
        if (!finite(value)) {
            return min;
        }
        return value < min ? min : value > max ? max : value;
    }

    private static boolean finite(float value) {
        return !Float.isNaN(value) && !Float.isInfinite(value);
    }

    private static String format(float value) {
        if (!finite(value)) {
            return "-";
        }
        return String.format(Locale.ROOT, "%.4f", Float.valueOf(value));
    }

    private static final class HelmetInfo {
        final int itemId;
        final String name;

        HelmetInfo(int itemId, String name) {
            this.itemId = itemId;
            this.name = name;
        }
    }

    public static final class Snapshot {
        public final boolean marioMode;
        public final int itemId;
        public final String itemName;
        public final float scale;
        public final float x;
        public final float y;
        public final float z;
        public final float yawDegrees;
        public final boolean frozen;
        public final boolean head3d;
        public final float faceAngle;
        public final boolean maskEnabled;
        public final boolean maskOnlyWithHelmet;
        public final float maskStartPercent;
        public final float maskRadiusPercent;
        public final int maskedTriangles;

        Snapshot(
                boolean marioMode,
                int itemId,
                String itemName,
                float scale,
                float x,
                float y,
                float z,
                float yawDegrees,
                boolean frozen,
                boolean head3d,
                float faceAngle,
                boolean maskEnabled,
                boolean maskOnlyWithHelmet,
                float maskStartPercent,
                float maskRadiusPercent,
                int maskedTriangles) {
            this.marioMode = marioMode;
            this.itemId = itemId;
            this.itemName = itemName;
            this.scale = scale;
            this.x = x;
            this.y = y;
            this.z = z;
            this.yawDegrees = yawDegrees;
            this.frozen = frozen;
            this.head3d = head3d;
            this.faceAngle = faceAngle;
            this.maskEnabled = maskEnabled;
            this.maskOnlyWithHelmet = maskOnlyWithHelmet;
            this.maskStartPercent = maskStartPercent;
            this.maskRadiusPercent = maskRadiusPercent;
            this.maskedTriangles = maskedTriangles;
        }
    }
}
